"""initial migration

Revision ID: 2898383789a9
Revises: None
Create Date: 2015-08-11 20:21:31.133252

"""

# revision identifiers, used by Alembic.
revision = '2898383789a9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
